# Generated by Django 2.2 on 2019-04-17 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('get_days', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DaysThreshold',
        ),
    ]
